# Generated by Django 4.2.14 on 2025-09-03 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0006_auto_20250831_2307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourismgallery',
            options={'ordering': ['order'], 'verbose_name': 'Galeri Paket Wisata', 'verbose_name_plural': 'Galeri Paket Wisata'},
        ),
        migrations.RemoveField(
            model_name='tourismgallery',
            name='alt_text',
        ),
        migrations.RemoveField(
            model_name='tourismgallery',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='tourismgallery',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='tourismgallery',
            name='media_type',
        ),
        migrations.RemoveField(
            model_name='tourismgallery',
            name='tourism_location',
        ),
        migrations.RemoveField(
            model_name='tourismgallery',
            name='video_file',
        ),
        migrations.RemoveField(
            model_name='tourismgallery',
            name='video_url',
        ),
        migrations.AlterField(
            model_name='tourismgallery',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Deskripsi Gambar'),
        ),
        migrations.AlterField(
            model_name='tourismgallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tourism/packages/gallery/', verbose_name='Gambar'),
        ),
        migrations.AlterField(
            model_name='tourismgallery',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='tourism.tourismpackage', verbose_name='Paket Wisata'),
        ),
        migrations.AlterField(
            model_name='tourismgallery',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Judul Gambar'),
        ),
    ]
