# Generated by Django 4.2.14 on 2025-09-04 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0007_alter_tourismgallery_options_and_more'),
    ]

    operations = [
    ]
