# Generated by Django 5.2.4 on 2025-08-26 23:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("references", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nama Kategori"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Deskripsi")),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Icon FontAwesome"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="blue", max_length=20, verbose_name="Warna"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Kategori Event",
                "verbose_name_plural": "Kategori Event",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Judul Event")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=250, unique=True, verbose_name="Slug"
                    ),
                ),
                ("description", models.TextField(verbose_name="Deskripsi Event")),
                (
                    "short_description",
                    models.TextField(
                        blank=True, max_length=300, verbose_name="Deskripsi Singkat"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Tanggal Mulai")),
                ("end_date", models.DateField(verbose_name="Tanggal Selesai")),
                ("start_time", models.TimeField(verbose_name="Waktu Mulai")),
                ("end_time", models.TimeField(verbose_name="Waktu Selesai")),
                (
                    "location",
                    models.CharField(max_length=200, verbose_name="Lokasi Event"),
                ),
                (
                    "address",
                    models.TextField(blank=True, verbose_name="Alamat Lengkap"),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Longitude",
                    ),
                ),
                (
                    "max_participants",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Maksimal Peserta"
                    ),
                ),
                (
                    "current_participants",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Peserta Saat Ini"
                    ),
                ),
                (
                    "allow_registration",
                    models.BooleanField(
                        default=True, verbose_name="Izinkan Pendaftaran"
                    ),
                ),
                (
                    "registration_deadline",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deadline Pendaftaran"
                    ),
                ),
                (
                    "is_free",
                    models.BooleanField(default=True, verbose_name="Event Gratis"),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Biaya Event",
                    ),
                ),
                (
                    "requirements",
                    models.TextField(blank=True, verbose_name="Persyaratan Peserta"),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Contact Person"
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="No. HP Contact"
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email Contact"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("ongoing", "Berlangsung"),
                            ("completed", "Selesai"),
                            ("cancelled", "Dibatalkan"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Rendah"),
                            ("normal", "Normal"),
                            ("high", "Tinggi"),
                            ("urgent", "Mendesak"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="Prioritas",
                    ),
                ),
                (
                    "featured_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="events/images/",
                        verbose_name="Gambar Utama",
                    ),
                ),
                (
                    "gallery_images",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Galeri Gambar"
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        verbose_name="Tags (pisahkan dengan koma)",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Catatan")),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Event Unggulan"),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Jumlah Dilihat"
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Rating",
                    ),
                ),
                (
                    "total_ratings",
                    models.PositiveIntegerField(default=0, verbose_name="Total Rating"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tanggal Dipublikasi"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Dibuat Oleh",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.eventcategory",
                        verbose_name="Kategori",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Event",
                "ordering": ["-start_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EventDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Judul Dokumen"),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("proposal", "Proposal"),
                            ("budget", "Anggaran"),
                            ("report", "Laporan"),
                            ("certificate", "Sertifikat"),
                            ("photo", "Foto"),
                            ("video", "Video"),
                            ("other", "Lainnya"),
                        ],
                        max_length=20,
                        verbose_name="Jenis Dokumen",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="events/documents/", verbose_name="File"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Deskripsi")),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Ukuran File (bytes)"
                    ),
                ),
                (
                    "download_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Jumlah Download"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="Publik"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="events.event",
                        verbose_name="Event",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Diupload Oleh",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dokumen Event",
                "verbose_name_plural": "Dokumen Event",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EventParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "registration_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Tanggal Daftar"
                    ),
                ),
                (
                    "registration_source",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("offline", "Offline"),
                            ("phone", "Telepon"),
                            ("walk_in", "Datang Langsung"),
                        ],
                        default="online",
                        max_length=20,
                        verbose_name="Sumber Pendaftaran",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Menunggu Konfirmasi"),
                            ("confirmed", "Dikonfirmasi"),
                            ("attended", "Hadir"),
                            ("absent", "Tidak Hadir"),
                            ("cancelled", "Dibatalkan"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="No. HP"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "emergency_contact",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Kontak Darurat"
                    ),
                ),
                (
                    "emergency_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="No. HP Darurat"
                    ),
                ),
                (
                    "special_needs",
                    models.TextField(blank=True, verbose_name="Kebutuhan Khusus"),
                ),
                (
                    "dietary_restrictions",
                    models.TextField(blank=True, verbose_name="Pantangan Makanan"),
                ),
                (
                    "check_in_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Waktu Check-in"
                    ),
                ),
                (
                    "check_out_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Waktu Check-out"
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("unpaid", "Belum Bayar"),
                            ("paid", "Sudah Bayar"),
                            ("partial", "Bayar Sebagian"),
                            ("refunded", "Dikembalikan"),
                        ],
                        default="unpaid",
                        max_length=20,
                        verbose_name="Status Pembayaran",
                    ),
                ),
                (
                    "payment_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Jumlah Bayar",
                    ),
                ),
                (
                    "payment_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tanggal Bayar"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Catatan")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Didaftarkan Oleh",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="events.event",
                        verbose_name="Event",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="references.penduduk",
                        verbose_name="Peserta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Peserta Event",
                "verbose_name_plural": "Peserta Event",
                "ordering": ["-registration_date"],
                "unique_together": {("event", "participant")},
            },
        ),
        migrations.CreateModel(
            name="EventRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=200, verbose_name="Nama Lengkap"),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="No. HP")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                ("address", models.TextField(verbose_name="Alamat")),
                (
                    "age",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Usia"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("male", "Laki-laki"), ("female", "Perempuan")],
                        max_length=10,
                        verbose_name="Jenis Kelamin",
                    ),
                ),
                (
                    "registration_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Tanggal Daftar"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Menunggu Konfirmasi"),
                            ("confirmed", "Dikonfirmasi"),
                            ("rejected", "Ditolak"),
                            ("cancelled", "Dibatalkan"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "special_needs",
                    models.TextField(blank=True, verbose_name="Kebutuhan Khusus"),
                ),
                (
                    "dietary_restrictions",
                    models.TextField(blank=True, verbose_name="Pantangan Makanan"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Catatan")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="events.event",
                        verbose_name="Event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pendaftaran Event",
                "verbose_name_plural": "Pendaftaran Event",
                "ordering": ["-registration_date"],
            },
        ),
        migrations.CreateModel(
            name="EventSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Judul Aktivitas"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Deskripsi")),
                ("start_time", models.TimeField(verbose_name="Waktu Mulai")),
                ("end_time", models.TimeField(verbose_name="Waktu Selesai")),
                (
                    "location",
                    models.CharField(blank=True, max_length=200, verbose_name="Lokasi"),
                ),
                (
                    "speaker",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Pembicara"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Urutan"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="events.event",
                        verbose_name="Event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Jadwal Event",
                "verbose_name_plural": "Jadwal Event",
                "ordering": ["order", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="EventFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Rating",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Komentar")),
                (
                    "organization_rating",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Rating Organisasi",
                    ),
                ),
                (
                    "venue_rating",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Rating Lokasi",
                    ),
                ),
                (
                    "content_rating",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Rating Konten",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="events.event",
                        verbose_name="Event",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.eventparticipant",
                        verbose_name="Peserta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feedback Event",
                "verbose_name_plural": "Feedback Event",
                "ordering": ["-created_at"],
                "unique_together": {("event", "participant")},
            },
        ),
    ]
