# Generated by Django 4.2.14 on 2025-08-27 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('references', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jabatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_jabatan', models.CharField(max_length=100, unique=True)),
                ('deskripsi', models.TextField(blank=True)),
                ('level_hierarki', models.PositiveIntegerField(default=1, help_text='1=Tertinggi, semakin besar semakin rendah')),
                ('warna_badge', models.CharField(default='#3B82F6', help_text='Kode warna hex untuk badge', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Jabatan',
                'verbose_name_plural': 'Jabatan',
                'ordering': ['level_hierarki', 'nama_jabatan'],
            },
        ),
        migrations.CreateModel(
            name='PeriodeKepengurusan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_periode', models.CharField(max_length=100)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('deskripsi', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periode_kepengurusan', to='organization.organization')),
            ],
            options={
                'verbose_name': 'Periode Kepengurusan',
                'verbose_name_plural': 'Periode Kepengurusan',
                'ordering': ['-tanggal_mulai'],
            },
        ),
        migrations.CreateModel(
            name='GaleriKegiatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('deskripsi', models.TextField(blank=True)),
                ('foto', models.ImageField(upload_to='organization/gallery/')),
                ('tanggal_kegiatan', models.DateField()),
                ('lokasi', models.CharField(blank=True, max_length=200)),
                ('fotografer', models.CharField(blank=True, max_length=100)),
                ('tags', models.CharField(blank=True, help_text='Pisahkan dengan koma', max_length=500)),
                ('is_featured', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeri', to='organization.organization')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Galeri Kegiatan',
                'verbose_name_plural': 'Galeri Kegiatan',
                'ordering': ['-tanggal_kegiatan', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnggotaOrganisasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_profil', models.ImageField(blank=True, null=True, upload_to='organization/profiles/')),
                ('nomor_anggota', models.CharField(blank=True, max_length=50)),
                ('tanggal_bergabung', models.DateField()),
                ('tanggal_keluar', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('non_aktif', 'Non Aktif'), ('keluar', 'Keluar'), ('pensiun', 'Pensiun')], default='aktif', max_length=20)),
                ('bio', models.TextField(blank=True, help_text='Biografi singkat anggota')),
                ('kontak_whatsapp', models.CharField(blank=True, max_length=20)),
                ('email_pribadi', models.EmailField(blank=True, max_length=254)),
                ('alamat_lengkap', models.TextField(blank=True)),
                ('pendidikan_terakhir', models.CharField(blank=True, max_length=100)),
                ('pekerjaan', models.CharField(blank=True, max_length=100)),
                ('keahlian', models.TextField(blank=True, help_text='Keahlian yang dimiliki')),
                ('prestasi', models.TextField(blank=True, help_text='Prestasi yang pernah diraih')),
                ('is_featured', models.BooleanField(default=False, help_text='Tampilkan di halaman utama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jabatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.jabatan')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anggota_detail', to='organization.organization')),
                ('penduduk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.penduduk')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.periodekepengurusan')),
            ],
            options={
                'verbose_name': 'Anggota Organisasi',
                'verbose_name_plural': 'Anggota Organisasi',
                'ordering': ['jabatan__level_hierarki', 'penduduk__name'],
                'unique_together': {('organization', 'penduduk', 'periode')},
            },
        ),
        migrations.CreateModel(
            name='StrukturOrganisasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posisi_x', models.IntegerField(default=0, help_text='Posisi horizontal dalam bagan')),
                ('posisi_y', models.IntegerField(default=0, help_text='Posisi vertikal dalam bagan')),
                ('urutan', models.PositiveIntegerField(default=1)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anggota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.anggotaorganisasi')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='struktur', to='organization.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='organization.strukturorganisasi')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.periodekepengurusan')),
            ],
            options={
                'verbose_name': 'Struktur Organisasi',
                'verbose_name_plural': 'Struktur Organisasi',
                'ordering': ['urutan', 'anggota__jabatan__level_hierarki'],
                'unique_together': {('organization', 'periode', 'anggota')},
            },
        ),
    ]
