# Generated by Django 4.2.14 on 2025-08-27 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_jabatan_galerikegiatan_periodekepengurusan_and_more'),
        ('organization', '0002_jabatan_periodekepengurusan_galerikegiatan_and_more'),
    ]

    operations = [
    ]
