# Generated by Django 4.2.14 on 2025-09-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_kepemudaan_media_sosial_kepemudaan_visi_misi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nama Organisasi')),
                ('organization_type', models.CharField(choices=[('perangkat_desa', 'Perangkat Desa'), ('lembaga_adat', 'Lembaga Adat'), ('pkk', 'Tim Penggerak PKK'), ('kepemudaan', 'Organisasi Kepemudaan'), ('karang_taruna', 'Karang Taruna'), ('bpd', 'Badan Permusyawaratan Desa'), ('lpm', 'Lembaga Pemberdayaan Masyarakat'), ('lainnya', 'Lainnya')], max_length=50, verbose_name='Jenis Organisasi')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('established_date', models.DateField(verbose_name='Tanggal Terbentuk')),
                ('address', models.TextField(blank=True, verbose_name='Alamat Sekretariat')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Nomor Telepon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('non_aktif', 'Non Aktif'), ('dalam_pembinaan', 'Dalam Pembinaan')], default='aktif', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organisasi',
                'verbose_name_plural': 'Data Organisasi',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='organizatio_name_2d216c_idx'), models.Index(fields=['organization_type'], name='organizatio_organiz_23b6f4_idx'), models.Index(fields=['status'], name='organizatio_status_6c2557_idx'), models.Index(fields=['organization_type', 'status'], name='organizatio_organiz_0e9580_idx')],
            },
        ),
    ]
