# Generated by Django 4.2.14 on 2025-09-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='kepemudaan',
            name='sk_kepengurusan',
            field=models.CharField(blank=True, help_text='Nomor SK Kepengurusan', max_length=100),
        ),
    ]
