# Generated by Django 4.2.14 on 2025-08-27 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posyandu', '0002_alter_posyanduschedule_created_by_ibuhamil_and_more'),
        ('posyandu', '0002_ibuhamil_alter_posyanduschedule_created_by_and_more'),
    ]

    operations = [
    ]
