# Generated by Django 4.2.14 on 2025-08-27 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('letters', '0002_letter_ai_generated_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikeysettings',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letters_api_key_created', to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letters_created', to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh'),
        ),
        migrations.AlterField(
            model_name='lettersettings',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letters_settings_created', to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh'),
        ),
        migrations.AlterField(
            model_name='lettertemplate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letters_template_created', to=settings.AUTH_USER_MODEL, verbose_name='Dibuat Oleh'),
        ),
    ]
