# Generated by Django 4.2.14 on 2025-09-04 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village_profile', '0004_villagehistoryphoto_delete_googlemapsemblem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VillageVision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Judul')),
                ('vision_text', models.TextField(verbose_name='Visi')),
                ('mission_text', models.TextField(verbose_name='Misi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('effective_date', models.DateField(verbose_name='Tanggal Berlaku')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui')),
            ],
            options={
                'verbose_name': 'Visi Misi Desa',
                'verbose_name_plural': 'Visi Misi Desa',
                'ordering': ['-effective_date'],
            },
        ),
    ]
